#!/bin/bash
#$ -l h_rt=240:0:0
#$ -l h_vmem=11G
#$ -pe smp 8
#$ -l gpu=1
#$ -l gpu_type=volta
#$ -cwd
#$ -j y
#$ -m b

set -e

# Replace the following line with a program or command
source /data/home/eey818/Diff-MST/env/bin/activate
python /data/home/eey818/Diff-MST/scripts/eval_all_combo.py

# Generated by Job Script Builder on 2025-10-18
# For assistance, please email its-research-support@qmul.ac.uk
# Please cite use of Apocrita in your Research
# See https://docs.hpc.qmul.ac.uk/using/citing/ for details
